[2021-11-29 12:32:54,503] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-01-12T00:00:00+00:00 [queued]>
[2021-11-29 12:32:55,230] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-01-12T00:00:00+00:00 [queued]>
[2021-11-29 12:32:55,230] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:32:55,231] {taskinstance.py:1068} INFO - Starting attempt 3 of 3
[2021-11-29 12:32:55,231] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:32:55,506] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_3> on 2020-01-12T00:00:00+00:00
[2021-11-29 12:32:55,628] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_3', '2020-01-12T00:00:00+00:00', '--job-id', '294', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmplxa3grse', '--error-file', '/tmp/tmpnsxaocuc']
[2021-11-29 12:32:55,662] {standard_task_runner.py:52} INFO - Started process 146069 to run task
[2021-11-29 12:32:55,936] {standard_task_runner.py:77} INFO - Job 294: Subtask task_3
[2021-11-29 12:32:57,503] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_3 2020-01-12T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:32:58,871] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2020-01-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-12T00:00:00+00:00
[2021-11-29 12:32:58,873] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:32:58,912] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:32:58,996] {subprocess.py:75} INFO - Output:
[2021-11-29 12:33:02,139] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:33:02,706] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_3, execution_date=20200112T000000, start_date=20211129T123254, end_date=20211129T123302
[2021-11-29 12:33:04,244] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:33:04,517] {local_task_job.py:151} INFO - Task exited with return code 0
