[2021-11-29 12:33:39,330] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-01-20T00:00:00+00:00 [queued]>
[2021-11-29 12:33:39,557] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-01-20T00:00:00+00:00 [queued]>
[2021-11-29 12:33:39,557] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:33:39,558] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2021-11-29 12:33:39,558] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:33:39,741] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_3> on 2020-01-20T00:00:00+00:00
[2021-11-29 12:33:39,789] {standard_task_runner.py:52} INFO - Started process 148929 to run task
[2021-11-29 12:33:39,799] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_3', '2020-01-20T00:00:00+00:00', '--job-id', '329', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpp_o2ahzv', '--error-file', '/tmp/tmpand0vt7n']
[2021-11-29 12:33:39,865] {standard_task_runner.py:77} INFO - Job 329: Subtask task_3
[2021-11-29 12:33:40,791] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_3 2020-01-20T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:33:41,910] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2020-01-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-20T00:00:00+00:00
[2021-11-29 12:33:41,966] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:33:41,966] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:33:42,210] {subprocess.py:75} INFO - Output:
[2021-11-29 12:33:45,346] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:33:45,788] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_3, execution_date=20200120T000000, start_date=20211129T123339, end_date=20211129T123345
[2021-11-29 12:33:47,513] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:33:47,559] {local_task_job.py:151} INFO - Task exited with return code 0
